# Site settings
title: FundRequest landingpage
email: info@fundrequest.io
description: "FundRequest - Boost open source"
keywords: "fundrequest, ico, github funding, issue funding, funding, ethereum, eth"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site
twitter_username: fundrequest_io
github_username:  FundRequest

# Build settings
markdown: kramdown